default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sagan-redux-development
  #username: quaker-crm
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: sagan-redux-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
